---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shlink-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: shlink-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "postgres/password" # TODO map to real 1Password item/field
    - secretKey: SHLINK_SERVER_API_KEY
      remoteRef:
        key: "shlink/api-key" # TODO map to real 1Password item/field
    - secretKey: GEOLITE_LICENSE_KEY
      remoteRef:
        key: "shlink/geoip-license" # TODO map to real 1Password item/field
