# From: https://raw.githubusercontent.com/portainer/k8s/master/deploy/manifests/portainer/portainer-lb.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - prefix-middleware.yml
  - ingress.yml
  - service-monitor.yml
  - prometheus-rule.yml
  - grafana-etcd-dashboard.yml
  - grafana-kubelet-dashboard.yml
  - grafana-kubernetes-api-server-dashboard.yml
  - grafana-kubernetes-controller-manager-dashboard.yml
  - grafana-kubernetes-proxy-dashboard.yml
  - grafana-kubernetes-scheduler-dashboard.yml
