apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  labels:
    app: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      volumes:
        - name: "config"
          persistentVolumeClaim:
            claimName: heimdall-pvc
      containers:
        - name: heimdall
          image: ghcr.io/linuxserver/heimdall:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /config
          ports:
            - name: svc-80-http
              containerPort: 80
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "300Mi"
              cpu: "500m"
