apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: heimdall

labels:
  - pairs:
      app: heimdall
    includeSelectors: true

configMapGenerator:
  - name: heimdall-configmap
    envs:
      - .env

resources:
  - namespace.yml
  - pvc.yml
  - deployment.yml
  - service.yml
  - ingress.yml
