# Taken from: https://picluster.ricsanfre.com/docs/prometheus/

prometheusOperator:
  # Relabeling job name for operator metrics
  serviceMonitor:
    relabelings:
    # Replace job value
    - sourceLabels:
      - __address__
      action: replace
      targetLabel: job
      replacement: prometheus-operator
  # Disable creation of kubelet service
  kubeletService:
    enabled: false
alertmanager:
  alertmanagerSpec:
    # Subpath /alertmanager configuration
    externalUrl: http://monitoring.${NETWORK_HOSTNAME_SUFFIX}/alertmanager/
    routePrefix: /
    # PVC configuration
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 25Gi
  # ServiceMonitor job relabel
  serviceMonitor:
    relabelings:
      # Replace job value
      - sourceLabels:
        - __address__
        action: replace
        targetLabel: job
        replacement: alertmanager
prometheus:
  prometheusSpec:
    # Subpath /prometheus configuration
    externalUrl: http://monitoring.${NETWORK_HOSTNAME_SUFFIX}/prometheus/
    routePrefix: /
    # Resources request and limits
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 1Gi
    # PVC configuration
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 25Gi
  # ServiceMonitor job relabel
  serviceMonitor:
    relabelings:
      # Replace job value
      - sourceLabels:
        - __address__
        action: replace
        targetLabel: job
        replacement: prometheus
grafana:
  # Configuring /grafana subpath
  grafana.ini:
    server:
      domain: monitoring.${NETWORK_HOSTNAME_SUFFIX}
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      serve_from_sub_path: true
  # Admin user password
  adminPassword: ${GRAFANA_PASSWORD}
  # Set timezone to be browser
  defaultDashboardsTimezone: browser
  # List of grafana plugins to be installed
  plugins:
    - grafana-piechart-panel
  persistence:
    enabled: true
    size: 25Gi
  # ServiceMonitor label and job relabel
  serviceMonitor:
    labels:
      release: monitoring
    relabelings:
      # Replace job value
      - sourceLabels:
        - __address__
        action: replace
        targetLabel: job
        replacement: grafana
  sidecar:
    dashboards:
      enabled: true
      labelValue: "1"
# Disabling monitoring of K8s services.
# Monitoring of K3S components will be configured out of monitoring
kubelet:
  enabled: false
kubeApiServer:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false
# Disable K8S Prometheus Rules
# Rules for K3S components will be configured out of monitoring
defaultRules:
  create: true
  rules:
    etcd: false
    k8s: false
    kubeApiserverAvailability: false
    kubeApiserverBurnrate: false
    kubeApiserverHistogram: false
    kubeApiserverSlos: false
    kubeControllerManager: false
    kubelet: false
    kubeProxy: false
    kubernetesApps: false
    kubernetesResources: false
    kubernetesStorage: false
    kubernetesSystem: false
    kubeScheduler: false