apiVersion: apps/v1
kind: Deployment
metadata:
  name: shlink-shortener
  labels:
    app: shlink
    component: shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shlink
      component: shortener
  template:
    metadata:
      labels:
        app: shlink
        component: shortener
    spec:
      containers:
        - name: shlink
          image: shlinkio/shlink:stable
          envFrom:
            - configMapRef:
                name: shlink-configmap
            - secretRef:
                name: shlink-secret
          ports:
            - name: 8080-tcp
              containerPort: 8080
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "100Mi"
              cpu: "0.25"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shlink-web
  labels:
    app: shlink
    component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shlink
      component: web
  template:
    metadata:
      labels:
        app: shlink
        component: web
    spec:
      containers:
        - name: shlink-web
          image: ghcr.io/shlinkio/shlink-web-client:4.3
          envFrom:
            - configMapRef:
                name: shlink-configmap
            - secretRef:
                name: shlink-secret
          ports:
            - name: 8080-tcp
              containerPort: 8080
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "100Mi"
              cpu: "0.25"
