apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

configMapGenerator:
  - name: grafana-uptime
    files:
      - grafana-dashboards/uptime.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "true"
  - name: grafana-node-exporter-full
    files:
      - grafana-dashboards/node-exporter-full-dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "true"
  - name: grafana-cluster-overview
    files:
      - grafana-dashboards/cluster-overview-dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "true"
  - name: grafana-coredns
    files:
      - grafana-dashboards/coredns-dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "true"
  - name: grafana-longhorn
    files:
      - grafana-dashboards/longhorn-dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "true"
  - name: grafana-cert-manager
    files:
      - grafana-dashboards/cert-manager-dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "true"

resources:
  - prefix-middleware.yml
  - ingress.yml
  - service-monitor.yml
  - prometheus-rule.yml
  - longhorn-service-monitor.yml
  - certmanager-service-monitor.yml
