apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pihole-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: pihole
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
