apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

labels:
  - pairs:
      app: pihole
    includeSelectors: true

configMapGenerator:
  - name: pihole-configmap
    envs:
      - .env

secretGenerator:
  - name: pihole-secret
    envs:
      - .env.secret.temp

resources:
  - statefulset.yml
  - service.yml
  - headless-service.yml
  - poddisruptionbudget.yml
  - ingress.yml
