apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pihole
spec:
  serviceName: pihole
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    spec:
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: pihole
          maxSkew: 2
          minDomains: 3
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
      containers:
        - name: pihole
          image: pihole/pihole:latest
          envFrom:
            - configMapRef:
                name: pihole-configmap
            - secretRef:
                name: pihole-secret
          ports:
            - name: svc-53-udp
              containerPort: 53
              protocol: UDP
            - name: svc-53-tcp
              containerPort: 53
              protocol: TCP
            - name: svc-ui
              containerPort: 80
              protocol: TCP
            - name: svc-ui-s
              containerPort: 443
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "800m"
            requests:
              memory: "128Mi"
              cpu: "200m"
          volumeMounts:
            - mountPath: /etc/pihole
              name: pihole-pvc
          securityContext:
            capabilities:
              add:
                - SYS_NICE
          livenessProbe:
            failureThreshold: 5
            timeoutSeconds: 20
            initialDelaySeconds: 300
            periodSeconds: 60
            httpGet:
              path: /admin/login.php
              port: svc-ui
          readinessProbe:
            failureThreshold: 10
            timeoutSeconds: 15
            initialDelaySeconds: 180
            periodSeconds: 30
            httpGet:
              path: /admin/login.php
              port: svc-ui
          startupProbe:
            failureThreshold: 60
            timeoutSeconds: 15
            initialDelaySeconds: 60
            periodSeconds: 15
            httpGet:
              path: /admin/login.php
              port: svc-ui
  volumeClaimTemplates:
    - metadata:
        name: pihole-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
