apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pihole
spec:
  serviceName: pihole
  updateStrategy:
    type: RollingUpdate
  template:
    spec:
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: pihole
          maxSkew: 1
          minDomains: 2
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
      containers:
        - name: pihole
          image: pihole/pihole:latest
          envFrom:
            - configMapRef:
                name: pihole-configmap
            - secretRef:
                name: pihole-secret
          ports:
            - name: svc-53-udp
              containerPort: 53
              protocol: UDP
            - name: svc-53-tcp
              containerPort: 53
              protocol: TCP
            - name: svc-ui
              containerPort: 80
              protocol: TCP
            - name: svc-ui-s
              containerPort: 443
              protocol: TCP
          resources:
            limits:
              memory: "1Gi"
              cpu: "0.5"
            requests:
              memory: "250Mi"
              cpu: "0.25"
          volumeMounts:
            - mountPath: /etc/pihole
              name: pihole-pvc
          securityContext:
            capabilities:
              add:
                - SYS_NICE
          livenessProbe:
            failureThreshold: 3
            timeoutSeconds: 60
            initialDelaySeconds: 90
            httpGet:
              path: /admin/login
              port: svc-ui
          readinessProbe:
            failureThreshold: 3
            timeoutSeconds: 60
            initialDelaySeconds: 90
            httpGet:
              path: /admin/login
              port: svc-ui
  volumeClaimTemplates:
    - metadata:
        name: pihole-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
