apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: changedetection-ingress
  annotations:
    cluster-config/suffix-host: "true"
    cluster-config/suffix-tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: security-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: changedetection.SUFFIX
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: changedetection-svc
                port:
                  name: 80-tcp
  tls:
    - secretName: changedetection-tls
      hosts:
        - changedetection.SUFFIX
