apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: changedetection

labels:
  - pairs:
      app: changedetection
    includeSelectors: true

configMapGenerator:
  - name: changedetection-configmap
    envs:
      - .env

resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - pdb.yml
  - pvc.yml
  - ingress.yml
