apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chrony

commonLabels:
  app: chrony

configMapGenerator:
  - name: chrony-configmap
    envs:
      - .env

resources:
  - namespace.yml
  - deployment.yml
  - service.yml
