apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localproxy-ender3-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: ender3.${NETWORK_HOSTNAME_SUFFIX}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: localproxy-ender3-svc
                port:
                  name: 80-tcp
