apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localproxy-cr10-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: cr10.${NETWORK_HOSTNAME_SUFFIX}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: localproxy-cr10-ui-svc
                port:
                  name: 80-tcp
