apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: localproxy

labels:
  - pairs:
      app: localproxy
    includeSelectors: true

resources:
  - namespace.yml
  - config.yml
  - deployment.yml
  - service.yml
  - ingress-cr10.yml
  - ingress-ender3.yml
  - ingress-nas.yml
  - ingress-scrypted.yml
  - ingress-homebridge.yml
