apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: security

labels:
  - pairs:
      app: security
    includeSelectors: true

resources:
  - namespace.yml
  - secrets.yml
  - middleware-basicauth.yml
  - middleware-https.yml
  - middleware-maxbody.yml
  - middleware-wss.yml
  - clusterissuer-letsencrypt.yml

