apiVersion: v1
kind: Namespace
metadata:
  name: homebridge
  labels:
    name: homebridge
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: homebridge
  name: homebridge-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homebridge-configmap
  namespace: homebridge
data:
  TZ: "${TIMEZONE}"
  PGID: "${PGID}"
  PUID: "${PUID}"
  HOMEBRIDGE_CONFIG_UI_PORT: "8081"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homebridge
  namespace: homebridge
  labels:
    app: homebridge
spec:
  serviceName: "homebridge"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: homebridge
  template:
    metadata:
      labels:
        app: homebridge
    spec:
      nodeSelector:
        homebridge: "true"
      containers:
        - name: homebridge
          image: docker.io/oznu/homebridge:latest
          envFrom:
            - configMapRef:
                name: homebridge-configmap
          resources:
            limits:
              memory: "1024M"
              cpu: "2"
            requests:
              memory: "512M"
              cpu: "1"
          ports:
            - name: svc-ui
              containerPort: 8081
            - name: svc-51826
              containerPort: 51826
            - name: svc-51827
              containerPort: 51827
            - name: svc-51828
              containerPort: 51828
            - name: svc-51829
              containerPort: 51829
          volumeMounts:
            - mountPath: /homebridge
              name: homebridge-root
      volumes:
        - name: homebridge-root
          persistentVolumeClaim:
            claimName: homebridge-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: homebridge-ui-svc
  namespace: homebridge
spec:
  selector:
    app: homebridge
  ports:
    - name: 8081-tcp
      port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: homebridge-svc-51826
  namespace: homebridge
spec:
  selector:
    app: homebridge
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: 51826-tcp
      port: 51826
status:
  loadBalancer:
    ingress:
      - ip: ${CLUSTER_HOSTNETWORKINGIPADDRESS}
---
apiVersion: v1
kind: Service
metadata:
  name: homebridge-svc-51827
  namespace: homebridge
spec:
  selector:
    app: homebridge
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: 51827-tcp
      port: 51827
status:
  loadBalancer:
    ingress:
      - ip: ${CLUSTER_HOSTNETWORKINGIPADDRESS}
---
apiVersion: v1
kind: Service
metadata:
  name: homebridge-svc-51828
  namespace: homebridge
spec:
  selector:
    app: homebridge
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: 51828-tcp
      port: 51828
status:
  loadBalancer:
    ingress:
      - ip: ${CLUSTER_HOSTNETWORKINGIPADDRESS}
---
apiVersion: v1
kind: Service
metadata:
  name: homebridge-svc-51829
  namespace: homebridge
spec:
  selector:
    app: homebridge
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: 51829-tcp
      port: 51829
status:
  loadBalancer:
    ingress:
      - ip: ${CLUSTER_HOSTNETWORKINGIPADDRESS}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homebridge-ingress
  namespace: homebridge
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: homebridge.${NETWORK_HOSTNAME_SUFFIX}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: homebridge-ui-svc
                port:
                  name: 8081-tcp
