version: "3.8"
services:
  homebridge:
    container_name: homebridge
    image: oznu/homebridge:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8081
      - TZ=America/Detroit
    volumes:
      - ./clusterfs/homebridge-homebridge-pvc-pvc-3db78598-5c79-460b-9c12-154276c41abf:/homebridge
