---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nebulasync-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: nebulasync-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: PRIMARY
      remoteRef:
        key: "nebulasync/primary" # TODO map to real 1Password item/field
    - secretKey: REPLICAS
      remoteRef:
        key: "nebulasync/replicas" # TODO map to real 1Password item/field
