---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: keycloak-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: "keycloak/admin-password" # TODO map to real 1Password item/field
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: "postgres/password" # TODO map to real 1Password item/field
