# TODO verify platform-vs-app: legacy speedtest resource directory is empty.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: speedtest

labels:
  - pairs:
      app: speedtest
    includeSelectors: true

resources:
  - namespace.yml
