# From: https://raw.githubusercontent.com/portainer/k8s/master/deploy/manifests/portainer/portainer-lb.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portainer

commonLabels:
  app: portainer

resources:
  - namespace.yml
  - serviceaccount.yml
  - pvc.yml
  - rbac.yml
  - deployment.yml
  - service.yml
  - ingress.yml
