apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-a-records-configmap
data:
  a-records: |
    # DeepStack Records
    local-data: "deepstack.${NETWORK_HOSTNAME_SUFFIX}. A ${CLUSTER_HOSTNETWORKINGIPADDRESS}"
    local-data-ptr: "${CLUSTER_HOSTNETWORKINGIPADDRESS} deepstack.${NETWORK_HOSTNAME_SUFFIX}."

    # Homebridge Records
    local-data: "homebridge.${NETWORK_HOSTNAME_SUFFIX}. A ${CLUSTER_HOSTNETWORKINGIPADDRESS}"
    local-data-ptr: "${CLUSTER_HOSTNETWORKINGIPADDRESS} homebridge.${NETWORK_HOSTNAME_SUFFIX}."

    # Pi-hole Records
    local-data: "pihole.${NETWORK_HOSTNAME_SUFFIX}. A ${CLUSTER_HOSTNETWORKINGIPADDRESS}"
    local-data-ptr: "${CLUSTER_HOSTNETWORKINGIPADDRESS} pihole.${NETWORK_HOSTNAME_SUFFIX}."

    # Pi-hole Records
    local-data: "pihole-0.${NETWORK_HOSTNAME_SUFFIX}. A ${CLUSTER_HOSTNETWORKINGIPADDRESS}"
    local-data-ptr: "${CLUSTER_HOSTNETWORKINGIPADDRESS} pihole-0.${NETWORK_HOSTNAME_SUFFIX}."

    # Portainer Records
    local-data: "portainer.${NETWORK_HOSTNAME_SUFFIX}. A ${CLUSTER_HOSTNETWORKINGIPADDRESS}"
    local-data-ptr: "${CLUSTER_HOSTNETWORKINGIPADDRESS} portainer.${NETWORK_HOSTNAME_SUFFIX}."

    # Monitoring Records
    local-data: "monitoring.${NETWORK_HOSTNAME_SUFFIX}. A ${CLUSTER_HOSTNETWORKINGIPADDRESS}"
    local-data-ptr: "${CLUSTER_HOSTNETWORKINGIPADDRESS} monitoring.${NETWORK_HOSTNAME_SUFFIX}."

    # Longhorn Records
    local-data: "storage.${NETWORK_HOSTNAME_SUFFIX}. A ${CLUSTER_HOSTNETWORKINGIPADDRESS}"
    local-data-ptr: "${CLUSTER_HOSTNETWORKINGIPADDRESS} storage.${NETWORK_HOSTNAME_SUFFIX}."

    # Minecraft Records
    local-data: "minecraft.${NETWORK_HOSTNAME_SUFFIX}. A ${CLUSTER_HOSTNETWORKINGIPADDRESS}"
    local-data-ptr: "${CLUSTER_HOSTNETWORKINGIPADDRESS} minecraft.${NETWORK_HOSTNAME_SUFFIX}."
