{
 "title": "Uptime - Metrics",
 "description": "A dashboard to visualize the uptime metrics from the uptime monitor.)",
 "tags": [ "uptime-kuma" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "type",
    "query": {
     "query": "label_values(monitor_response_time, monitor_type)"
    }
   },
   {
    "name": "monitor",
    "query": {
     "query": "label_values(monitor_response_time{monitor_type=~\"$type\"}, monitor_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Monitors",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(monitor_status)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Online Monitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(monitor_status == 1)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Offline Monitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(monitor_status == 0)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average response time (2h)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(monitor_response_time[2h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "$monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "monitor" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"$monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 15, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_response_time{monitor_name=~\"$monitor\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "avg_over_time(monitor_response_time{monitor_name=~\"$monitor\"}[24h])",
     "legendFormat": "AVG 24H"
    }
   ]
  }
 ]
}