---
# Headless service for K3S metrics. No selector
apiVersion: v1
kind: Service
metadata:
  name: k3s-metrics-service
  labels:
    app.kubernetes.io/name: kubelet
spec:
  clusterIP: None
  ports:
    - name: https-metrics
      port: 10250
      protocol: TCP
      targetPort: 10250
  type: ClusterIP
---
# Endpoint for the headless service without selector
apiVersion: v1
kind: Endpoints
metadata:
  name: k3s-metrics-service
subsets:
  - addresses:
      - ip: 10.42.0.0
      - ip: 10.42.1.0
      - ip: 10.42.2.0
      - ip: 10.42.3.0
    ports:
      - name: https-metrics
        port: 10250
        protocol: TCP
