apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

configMapGenerator:
  - name: orbitalsync-configmap
    envs:
      - .env

resources:
  - deployment-orbitalsync.yml
