# Descheduler for Kubernetes
# https://github.com/kubernetes-sigs/descheduler/tree/master/charts/descheduler

# Run as a CronJob (default) or Job
kind: CronJob

# Schedule for CronJob (every 30 minutes)
schedule: "*/30 * * * *"

# Descheduler configuration
deschedulerPolicy:
  # Global namespace exclusions - avoid critical system namespaces
  nodeResourceUtilizationThresholds:
    # Exclude critical namespaces from descheduling
    includedNamespaces: []
    excludedNamespaces:
      - longhorn-system     # Longhorn storage system
      - kube-system        # Core Kubernetes system
      - kube-public        # Public Kubernetes resources
      - kube-node-lease    # Node lease objects
      - cert-manager       # Certificate management

  strategies:
    # Remove duplicate pods
    RemoveDuplicates:
      enabled: true
      params:
        excludeOwnerKinds:
          - DaemonSet          # Don't touch DaemonSets (Longhorn uses these)
          - StatefulSet        # Don't touch StatefulSets (Longhorn uses these)
        excludedNamespaces:
          - longhorn-system
          - kube-system

    # Remove pods that are running longer than specified time
    PodLifeTime:
      enabled: true
      params:
        podLifeTime:
          maxPodLifeTimeSeconds: 86400  # 24 hours
        excludeOwnerKinds:
          - DaemonSet          # Don't touch DaemonSets
          - StatefulSet        # Don't touch StatefulSets
        excludedNamespaces:
          - longhorn-system
          - kube-system

    # Remove pods violating inter-pod anti-affinity
    RemovePodsViolatingInterPodAntiAffinity:
      enabled: true
      params:
        excludeOwnerKinds:
          - DaemonSet
          - StatefulSet
        excludedNamespaces:
          - longhorn-system
          - kube-system

    # Remove pods violating node affinity
    RemovePodsViolatingNodeAffinity:
      enabled: true
      params:
        nodeAffinityType:
          - requiredDuringSchedulingIgnoredDuringExecution
        excludeOwnerKinds:
          - DaemonSet
          - StatefulSet
        excludedNamespaces:
          - longhorn-system
          - kube-system

    # Remove pods violating node taints
    RemovePodsViolatingNodeTaints:
      enabled: true
      params:
        excludeOwnerKinds:
          - DaemonSet
          - StatefulSet
        excludedNamespaces:
          - longhorn-system
          - kube-system

    # Remove failed pods
    RemoveFailedPods:
      enabled: true
      params:
        failedPods:
          reasons:
            - OutOfcpu
            - CreateContainerConfigError
          includingInitContainers: true
          excludeOwnerKinds:
            - Job
            - DaemonSet
            - StatefulSet
          minPodLifetimeSeconds: 3600  # 1 hour
        excludedNamespaces:
          - longhorn-system
          - kube-system

# Resource limits and requests
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# Node selector for scheduling the descheduler
nodeSelector:
  kubernetes.io/os: linux

# Tolerations (if needed for master nodes)
tolerations: []

# Pod disruption budget
podDisruptionBudget:
  enabled: false

# Service account
serviceAccount:
  create: true
  name: ""

# RBAC
rbac:
  create: true

# Priority class
priorityClassName: ""

# Image configuration
image:
  repository: registry.k8s.io/descheduler/descheduler
  tag: ""  # Uses chart appVersion if not specified
  pullPolicy: IfNotPresent

# Additional command line arguments
cmdOptions:
  v: 2  # Verbosity level

# Dry run mode (set to true for testing)
dryRun: false