apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-configmap
data:
  TZ: "${TIMEZONE}"
  ADMIN_EMAIL: "${REPLY_EMAIL}"
  PIHOLE_DNS_: 10.43.100.20
  CUSTOM_CACHE_SIZE: "0"
---
apiVersion: v1
kind: Secret
metadata:
  name: pihole-secret
data:
  WEBPASSWORD: ${PIHOLE_PASSWORD}
