apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

commonLabels:
  app: pihole

configMapGenerator:
  - name: pihole-configmap
    envs:
      - .env

secretGenerator:
- name: pihole-secret
  envs:
  - .env.secret

resources:
  - namespace.yml
  - pvc.yml
  - statefulset.yml
  - service.yml
  - ingress.yml
