apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pihole
spec:
  serviceName: "pihole"
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          envFrom:
            - configMapRef:
                name: pihole-configmap
            - secretRef:
                name: pihole-secret
          ports:
            - name: svc-53-udp
              containerPort: 53
              protocol: UDP
            - name: svc-53-tcp
              containerPort: 53
              protocol: TCP
            - name: svc-ui
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: "1Gi"
              cpu: "2"
            requests:
              memory: "100Mi"
              cpu: "250m"
          volumeMounts:
            - mountPath: /etc/pihole
              name: pihole-etc
      volumes:
        - name: pihole-etc
          persistentVolumeClaim:
            claimName: pihole-pvc
