apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pihole
spec:
  serviceName: "pihole"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          envFrom:
            - configMapRef:
                name: pihole-configmap
            - secretRef:
                name: pihole-secret
          ports:
            - name: svc-53-udp
              containerPort: 53
              protocol: UDP
            - name: svc-53-tcp
              containerPort: 53
              protocol: TCP
            - name: svc-ui
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: "250Mi"
              cpu: "100m"
            requests:
              memory: "150Mi"
              cpu: "20m"
          volumeMounts:
            - mountPath: /etc/pihole
              name: pihole-pvc
  volumeClaimTemplates:
    - metadata:
        name: pihole-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
