apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minecraft

labels:
  - pairs:
      app: minecraft
    includeSelectors: true

configMapGenerator:
  - name: minecraft-configmap
    envs:
      - .env

resources:
  - namespace.yml
  - statefulset.yml
  - service.yml
