apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-ingress
  annotations:
    cluster-config/suffix-host: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: pihole.SUFFIX
      http:
        paths:
          - pathType: Prefix
            path: /admin
            backend:
              service:
                name: pihole-ui-svc
                port:
                  name: 80-tcp
          - pathType: Prefix
            path: /api
            backend:
              service:
                name: pihole-ui-svc
                port:
                  name: 80-tcp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-0-ingress
  annotations:
    cluster-config/suffix-host: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: pihole-0.SUFFIX
      http:
        paths:
          - pathType: Prefix
            path: /admin
            backend:
              service:
                name: pihole-0-ui-svc
                port:
                  name: 80-tcp
          - pathType: Prefix
            path: /api
            backend:
              service:
                name: pihole-0-ui-svc
                port:
                  name: 80-tcp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-1-ingress
  annotations:
    cluster-config/suffix-host: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: pihole-1.SUFFIX
      http:
        paths:
          - pathType: Prefix
            path: /admin
            backend:
              service:
                name: pihole-1-ui-svc
                port:
                  name: 80-tcp
          - pathType: Prefix
            path: /api
            backend:
              service:
                name: pihole-1-ui-svc
                port:
                  name: 80-tcp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-2-ingress
  annotations:
    cluster-config/suffix-host: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: pihole-2.SUFFIX
      http:
        paths:
          - pathType: Prefix
            path: /admin
            backend:
              service:
                name: pihole-2-ui-svc
                port:
                  name: 80-tcp
          - pathType: Prefix
            path: /api
            backend:
              service:
                name: pihole-2-ui-svc
                port:
                  name: 80-tcp
