# local-zone: "themartinez.cloud." transparent
# local-data: "themartinez.cloud. IN A 192.168.52.110"
# local-data: "*.themartinez.cloud. IN A 192.168.52.110"
# local-data: "rpi001.themartinez.cloud. IN A 192.168.52.110"
# local-data-ptr: "192.168.52.110 rpi001.themartinez.cloud."
