apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pikaraoke

labels:
  - pairs:
      app: pikaraoke
    includeSelectors: true

configMapGenerator:
  - name: pikaraoke-configmap
    envs:
      - .env

resources:
  - namespace.yml
  - pvc.yml
  - deployment.yml
  - service.yml
  - ingress.yml
