apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portainer

labels:
  - pairs:
      app: portainer
    includeSelectors: true

resources:
  - namespace.yml
  - serviceaccount.yml
  - pvc.yml
  - rbac.yml
  - deployment.yml
  - service.yml
  - ingress.yml
