---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: uptime-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: uptime-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: UPTIME_USERNAME
      remoteRef:
        key: "uptime/username" # TODO map to real 1Password item/field
    - secretKey: UPTIME_PASSWORD
      remoteRef:
        key: "uptime/password" # TODO map to real 1Password item/field
