apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: uptime-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: uptime
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
