apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uptime

labels:
  - pairs:
      app: uptime
    includeSelectors: true

components:
  - ../../components/cluster-config

configMapGenerator:
  - name: uptime-configmap
    envs:
      - .env
  - name: uptime-mariadb-config
    files:
      - mariadb-tuning.cnf

resources:
  - namespace.yml
  - data-pvc.yml
  - deployment.yml
  - service.yml
  - pdb.yml
  - ingress.yml
  - mariadb-pvc.yml
  - mariadb-statefulset.yml
  - mariadb-service.yml
  - mariadb-pdb.yml
