apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
spec:
  template:
    spec:
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: pihole
          maxSkew: 1
          minDomains: 2
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
      containers:
        - name: unbound
          image: mvance/unbound-rpi:latest
          ports:
            - name: svc-53-udp
              containerPort: 53
              protocol: UDP
            - name: svc-53-tcp
              containerPort: 53
              protocol: TCP
          resources:
            limits:
              memory: "50Mi"
              cpu: "50m"
            requests:
              memory: "50Mi"
              cpu: "50m"
          volumeMounts:
            - mountPath: /opt/unbound/etc/unbound/a-records.conf
              name: unbound-config-files
              subPath: a-records.conf
            - mountPath: /opt/unbound/etc/unbound/unbound.conf
              name: unbound-config-files
              subPath: unbound.conf
          livenessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 25
            periodSeconds: 5
      volumes:
        - name: unbound-config-files
          configMap:
            name: unbound-configmap
            items:
              - key: a-records.conf
                path: a-records.conf
              - key: unbound.conf
                path: unbound.conf
