apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: unbound-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: unbound
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60
