apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

labels:
  - pairs:
      app: unbound
    includeSelectors: true

configMapGenerator:
  - name: unbound-configmap
    files:
      - a-records.conf

resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - horizontalpodautoscaler.yml
