apiVersion: v1
kind: Service
metadata:
  name: unbound-service
spec:
  selector:
    app: unbound
  type: ClusterIP
  clusterIP: 10.43.100.20
  sessionAffinity: ClientIP
  ports:
    - name: 53-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: 53-tcp
      port: 53
      targetPort: 53
      protocol: TCP
