apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebulasync
spec:
  template:
    spec:
      containers:
        - name: nebulasync
          image: ghcr.io/lovelaze/nebula-sync:latest
          envFrom:
            - configMapRef:
                name: nebulasync-configmap
            - secretRef:
                name: nebulasync-secret
          resources:
            limits:
              memory: "100Mi"
              cpu: "20m"
            requests:
              memory: "100Mi"
              cpu: "20m"

