apiVersion: v1
kind: ConfigMap
metadata:
  name: deepstack-configmap
  namespace: deepstack
data:
  TZ: "${TIMEZONE}"
  PGID: "${PGID}"
  PUID: "${PUID}"
  VISION-DETECTION: "True"
  VISION-SCENE: "True"
