apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepstack
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: deepstack
          image: deepquestai/deepstack:arm64-2021.06.1
          envFrom:
            - configMapRef:
                name: deepstack-configmap
          ports:
            - name: svc-ui
              containerPort: 5000
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
            requests:
              memory: "800Mi"
              cpu: "1"
          volumeMounts:
            - mountPath: /datastore
              name: deepstack-datastore
            - mountPath: /modelstore/detection
              name: deepstack-modelstore
      volumes:
        - name: deepstack-datastore
          persistentVolumeClaim:
            claimName: deepstack-datastore-pvc
        - name: deepstack-modelstore
          persistentVolumeClaim:
            claimName: deepstack-modelstore-pvc
