apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deepstack-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deepstack
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
  
