apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: deepstack

commonLabels:
  app: deepstack

resources:
  - namespace.yml
  - pvc.yml
  - configmap.yml
  - deployment.yml
  - service.yml
  - ingress.yml
