apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: meal-planner

labels:
  - pairs:
      app: meal-planner
    includeSelectors: true

configMapGenerator:
  - name: meal-planner-configmap
    envs:
      - .env

secretGenerator:
  - name: meal-planner-secret
    envs:
      - .env.secret.temp

resources:
  - namespace.yml
  - deployment.yml
  - horizontalpodautoscaler.yml
  - service.yml
  - ingress.yml
  - pdb.yml
