apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime
  template:
    metadata:
      labels:
        app: uptime
    spec:
      volumes:
        - name: "uptime"
          persistentVolumeClaim:
            claimName: uptime-pvc-rwo
      containers:
        - name: uptime
          image: louislam/uptime-kuma:1.23.16
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: uptime-configmap
          volumeMounts:
            - name: uptime
              mountPath: /app/data
          ports:
            - name: 3001-tcp
              containerPort: 3001
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 30
          startupProbe:
            httpGet:
              path: /
              port: 3001
            failureThreshold: 10
            periodSeconds: 10
