apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uptime

labels:
  - pairs:
      app: uptime
    includeSelectors: true

configMapGenerator:
  - name: uptime-configmap
    envs:
      - .env

resources:
  - namespace.yml
  - pvc-local.yml
  - pvc-backup.yml
  - deployment.yml
  - service.yml
  - ingress.yml
  - backup-cronjob.yml
