apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minecraft

commonLabels:
  app: minecraft

configMapGenerator:
  - name: minecraft-configmap
    envs:
      - .env

resources:
  - namespace.yml
  - pvc.yml
  - statefulset.yml
  - service.yml
