apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
spec:
  serviceName: "minecraft"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: minecraft
          image: 05jchambers/legendary-bedrock-container:latest
          tty: true
          stdin: true
          envFrom:
            - configMapRef:
                name: minecraft-configmap
          ports:
            - name: svc-19120-udp
              containerPort: 19120
              protocol: UDP
            - name: svc-19120-tcp
              containerPort: 19120
              protocol: TCP
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
          volumeMounts:
            - mountPath: /minecraft
              name: minecraft
      volumes:
        - name: minecraft
          persistentVolumeClaim:
            claimName: minecraft-pvc
