apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
spec:
  serviceName: "minecraft"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: minecraft
          image: 05jchambers/legendary-bedrock-container:latest
          tty: true
          stdin: true
          envFrom:
            - configMapRef:
                name: minecraft-configmap
          ports:
            - name: svc-19120-udp
              containerPort: 19120
              protocol: UDP
            - name: svc-19120-tcp
              containerPort: 19120
              protocol: TCP
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
            requests:
              memory: "500Mi"
              cpu: "250m"
          volumeMounts:
            - mountPath: /minecraft
              name: minecraft-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ipv4Only
                operator: DoesNotExist
  volumeClaimTemplates:
    - metadata:
        name: minecraft-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
