---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pikaraoke-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: pikaraoke-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: PIKARAOKE_ADMIN_PASSWORD
      remoteRef:
        key: "pikaraoke/admin-password" # TODO map to real 1Password item/field
