apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: deepstack

commonLabels:
  app: deepstack

configMapGenerator:
  - name: deepstack-configmap
    envs:
      - .env

resources:
  - namespace.yml
  - pvc.yml
  - deployment.yml
  - service.yml
  - horizontalpodautoscaler.yml
  - ingress.yml
